spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/roll_dice
    username: myUser
    password: P@ssw0rd123!
  profiles:
    include: ec2