spring:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./db;AUTO_SERVER=TRUE
    username: patryk
    password: qwerty
  h2:
    console:
      enabled: true
      path: /h2-console